---
- name:
  hosts: localhost
  tasks:
    - name: exec:ls -la
      command: ls -la
      register: result
      
    - name:
      debug:
        var: result
        
    - name: exec:pwd
      command: pwd
      register: result
      
    - name:
      debug:
        var: result
    
