---
- name:
  hosts: localhost
  tasks:
    - name: exec:ls -la
      command: ls -la
      register: result
      
    - name:
      debug:
        var: result
        
    - name: exec:pwd
      command: pwd
      register: result
      
    - name:
      debug:
        var: result
        
    - name: exec:who
      command: who
      register: result
      
    - name:
      debug:
        var: result
                
    - name: exec:id
      command: id
      register: result
      
    - name:
      debug:
        var: result
        
    - name: exec:ls -la
      command: ls -la /home/ec2-user
      register: result
      
    - name:
      debug:
        var: result
        
    - name: exec:ls -la
      command: ls -la /home/ec2-user/WIN
      register: result
      
    - name:
      debug:
        var: result
    
